name: echo

on: workflow_dispatch
#  schedule:
#    - cron: '42 0 * * *'  # Run once per day, to avoid Coverity's submission limits

#permissions:
#  contents: read # to fetch code (actions/checkout)

jobs:
  scan:
    runs-on: ubuntu-22.04

#    env:
#      CC: gcc
#      DEBIAN_FRONTEND: noninteractive
#      TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}

    steps:
      - run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - run: "ls -l"

      - name: Checkout repository from github
##       if: env.TOKEN
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."

